public enum ErrorType {
    INVALID_LOCATION,
    INVALID_ROLE,
    INVALID_RANK,
    NOT_AT_OFFICE,
    NO_ROLES,

    ALREADY_MOVED,
    ALREADY_WORKED,
    MOVE_WHILE_WORKING,
    TAKE_WHILE_WORKING,
    TAKE_AND_WORK,
    WORK_AND_MOVE,
    ACT_WHILE_NOT_WORKING,
    REHEARSE_WHILE_NOT_WORKING
}